on:
  workflow_call:
    inputs:
      yamldirs:
        required: false
        type: string
        default: "."

jobs:
  golangci_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        env:
          GOLANGCILINT_VERSION: v1.52-alpine
        shell: bash
        run: docker run -v $PWD:/work -w /work golangci/golangci-lint:v1.52-alpine golangci-lint run

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: hadolint
        env:
          HADOLINT_VERSION: 2.12.0-alpine
        shell: bash
        run: find . -name "Dockerfile*" -print  | xargs -r -n1 docker run -v "$PWD":/work -w /work "hadolint/hadolint:${HADOLINT_VERSION}" hadolint

  renovate-validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: renovate-validate
        env:
          RENOVATE_VERSION: "35"
        shell: bash
        run: docker run -v "$PWD":/work -w /work renovate/renovate renovate-config-validator 

  shellcheck-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: shellcheck-lint
        env:
          SHELLCHECK_VERSION: v0.9.0
        shell: bash
        run: find . -name "*.sh" -print  | xargs -r -n1 docker run -v "$PWD":/work -w /work "koalaman/shellcheck-alpine:${SHELLCHECK_VERSION}" shellcheck

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: yamllint
        shell: bash
        run: find ${{ inputs.yamldirs }} -name "*.yml" -or -name "*.yaml" -print  | xargs -r -n1 docker run -v "$PWD":/work -w /work cytopia/yamllint
